### ISSUE TITLE
Changing mime-words encoding

### ISSUE THREAD

**Issue by andris9** [emailjs/emailjs-mime-builder#14]
Current behavior for mimeWordEncode in mimefuncs module is to use quote-printable as the default encoding. Mime-words are mostly used for the name parts of addresses, subject lines and such. While quoted-printable is fine for languages using latin-based charsets because of being human readable, it doesn't make much sense to use it for non-latin languages like russian or chinese. In this case using base64 would be much better – resulting strings would be a lot shorter which would eliminate the need to wrap lines in a lot of cases.

Example subject line: _Привет и до свидания_

Current behavior (152 bytes, requires line wrapping):

```
Subject: =?UTF-8?Q?=D0=9F=D1=80=D0=B8=D0=B2=D0=B5=D1=82_?= =?UTF-8?Q?=D0=B8_=D0=B4=D0=BE_=D1=81=D0=B2=D0=B8?= =?UTF-8?Q?=D0=B4=D0=B0=D0=BD=D0=B8=D1=8F?=
```

Suggested behavior (73 bytes, does not require line wrapping):

```
Subject: =?UTF-8?B?0J/RgNC40LLQtdGCINC4INC00L4g0YHQstC40LTQsNC90LjRjw==?=
```

Both cases end up with an unreadable value, so using quoted-printable over base64 gives no advantage.

**Comment by felixhammerl** [comment]
here's a question...

So I've implemented a correct b64 encoding here: https://github.com/emailjs/emailjs-mime-codec/blob/master/src/mimecodec.js#L139-L140

However, the [RFC](https://tools.ietf.org/html/rfc2047#section-5) only states the following:

    The 'encoded-text' in an 'encoded-word' must be self-contained;
    'encoded-text' MUST NOT be continued from one 'encoded-word' to
    another.  This implies that the 'encoded-text' portion of a "B"
    'encoded-word' will be a multiple of 4 characters long; for a "Q"
    'encoded-word', any "=" character that appears in the 'encoded-text'
    portion will be followed by two hexadecimal characters.
    
    Each 'encoded-word' MUST encode an integral number of octets.  The
    'encoded-text' in each 'encoded-word' must be well-formed according
    to the encoding specified; the 'encoded-text' may not be continued in
    the next 'encoded-word'.  (For example, "=?charset?Q?=?=
    =?charset?Q?AB?=" would be illegal, because the two hex digits "AB"
    must follow the "=" in the same 'encoded-word'.)

So right now I'm not splitting octets, however I'm likely ripping apart the multibyte chars, which is running contrary to the RFC. Damn.
